// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        (unknown)
// source: gobox.proto

package gobox

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MeowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MeowRequest) Reset() {
	*x = MeowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gobox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeowRequest) ProtoMessage() {}

func (x *MeowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gobox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeowRequest.ProtoReflect.Descriptor instead.
func (*MeowRequest) Descriptor() ([]byte, []int) {
	return file_gobox_proto_rawDescGZIP(), []int{0}
}

func (x *MeowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MeowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meow string `protobuf:"bytes,1,opt,name=meow,proto3" json:"meow,omitempty"`
}

func (x *MeowResponse) Reset() {
	*x = MeowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gobox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeowResponse) ProtoMessage() {}

func (x *MeowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gobox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeowResponse.ProtoReflect.Descriptor instead.
func (*MeowResponse) Descriptor() ([]byte, []int) {
	return file_gobox_proto_rawDescGZIP(), []int{1}
}

func (x *MeowResponse) GetMeow() string {
	if x != nil {
		return x.Meow
	}
	return ""
}

var File_gobox_proto protoreflect.FileDescriptor

var file_gobox_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x6f, 0x62, 0x6f, 0x78, 0x22, 0x21, 0x0a, 0x0b, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x32, 0x3a, 0x0a, 0x05, 0x47,
	0x6f, 0x42, 0x6f, 0x78, 0x12, 0x31, 0x0a, 0x04, 0x4d, 0x65, 0x6f, 0x77, 0x12, 0x12, 0x2e, 0x67,
	0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x68, 0x65, 0x6e, 0x6a, 0x61, 0x79,
	0x61, 0x6b, 0x61, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x6f, 0x78, 0x2f, 0x67, 0x6f, 0x62, 0x6f,
	0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gobox_proto_rawDescOnce sync.Once
	file_gobox_proto_rawDescData = file_gobox_proto_rawDesc
)

func file_gobox_proto_rawDescGZIP() []byte {
	file_gobox_proto_rawDescOnce.Do(func() {
		file_gobox_proto_rawDescData = protoimpl.X.CompressGZIP(file_gobox_proto_rawDescData)
	})
	return file_gobox_proto_rawDescData
}

var file_gobox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gobox_proto_goTypes = []interface{}{
	(*MeowRequest)(nil),  // 0: gobox.MeowRequest
	(*MeowResponse)(nil), // 1: gobox.MeowResponse
}
var file_gobox_proto_depIdxs = []int32{
	0, // 0: gobox.GoBox.Meow:input_type -> gobox.MeowRequest
	1, // 1: gobox.GoBox.Meow:output_type -> gobox.MeowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gobox_proto_init() }
func file_gobox_proto_init() {
	if File_gobox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gobox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gobox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gobox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gobox_proto_goTypes,
		DependencyIndexes: file_gobox_proto_depIdxs,
		MessageInfos:      file_gobox_proto_msgTypes,
	}.Build()
	File_gobox_proto = out.File
	file_gobox_proto_rawDesc = nil
	file_gobox_proto_goTypes = nil
	file_gobox_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoBoxClient is the client API for GoBox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoBoxClient interface {
	Meow(ctx context.Context, in *MeowRequest, opts ...grpc.CallOption) (*MeowResponse, error)
}

type goBoxClient struct {
	cc grpc.ClientConnInterface
}

func NewGoBoxClient(cc grpc.ClientConnInterface) GoBoxClient {
	return &goBoxClient{cc}
}

func (c *goBoxClient) Meow(ctx context.Context, in *MeowRequest, opts ...grpc.CallOption) (*MeowResponse, error) {
	out := new(MeowResponse)
	err := c.cc.Invoke(ctx, "/gobox.GoBox/Meow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoBoxServer is the server API for GoBox service.
type GoBoxServer interface {
	Meow(context.Context, *MeowRequest) (*MeowResponse, error)
}

// UnimplementedGoBoxServer can be embedded to have forward compatible implementations.
type UnimplementedGoBoxServer struct {
}

func (*UnimplementedGoBoxServer) Meow(context.Context, *MeowRequest) (*MeowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meow not implemented")
}

func RegisterGoBoxServer(s *grpc.Server, srv GoBoxServer) {
	s.RegisterService(&_GoBox_serviceDesc, srv)
}

func _GoBox_Meow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBoxServer).Meow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobox.GoBox/Meow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBoxServer).Meow(ctx, req.(*MeowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoBox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobox.GoBox",
	HandlerType: (*GoBoxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meow",
			Handler:    _GoBox_Meow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gobox.proto",
}
